config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  resources :restaurants do
    resources :reservations
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true
  validates :password, presence: true

  has_many :reservations
  has_many :restaurants, through: :reservations

  def self.authenticate(email, password)
    user = find_by_email(email)
      if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
    user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  @user = User.new
  end

def create
  @user = User.new(user_params)
  #@restaurant = Restaurant.find(params[:restaurant_id])
  if @user.save
    flash[:notice] = "Yo signed up!"
    log_in @user
    redirect_to restaurants_url(route_params[:restaurant_id])
  else
    flash[:notice] = "Try again yo!"
    render "new"
  end
end

def show
  @user = User.find(params[:id])
end

def edit
  @user = User.find(params[:id])
end

def update
  @user = User.find(params[:id])

  if @user.update_attributes(user_params)
    flash[:notice] = "Yo up to date!"
    redirect_to user_url(@user)
  else
    flash[:notice] = "Try again yo!"
    render :edit
  end
end

private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name, :phone)
  end

  def route_params
    params.require(:user).permit(:restaurant_id)
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def log_in(user)
    session[:user_id] = user.id
  end
end

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |m| %>
      <li><%= m %></li>
      <% end %>
  </ul>
<% end %>

<div class="form">
<%= form_for @user do |f| %>
  <p>
    <%= f.label :name  %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email  %><br>
    <%= f.email_field :email %>
  </p>
  <p>
    <%= f.label :phone  %><br>
    <%= f.telephone_field :phone %>
  </p>
  <p>
    <%= f.label :password  %><br>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation  %><br>
    <%= f.password_field :password_confirmation %>
  </p>
  <p>
    <%= f.hidden_field :restaurant_id, value: restaurant %>
  </p>

  <%= f.submit "Submit" %>

<% end %>
</div>

app/views/users/create.html.erb
<!-- <h1>Create a New User to Seat YoSelf</h1>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/edit.html.erb
<%= link_to 'Back to Restaurants', restaurants_path %>

<h2>Edit Profile</h2>

<%= render 'form', user: @user %></br>

<%= link_to "Back to #{@user.name}'s Profile", user_path(@user) %>

app/views/users/index.html.erb
<div class="main">
  <div class="container">
    <h1>Yes, you <em>can</em> sit with us.</h1>
    <div class="search">
      <h2>Let's find a table.</h2>
      <p><%= form_tag(restaurants_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Restaurants" %>
      <%= submit_tag "Search" %>
      <% end %></p>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render 'form', restaurant: params[:restaurant] %>

<p>Already have an account? <%= link_to "Log in", new_session_path %></p>

app/views/users/show.html.erb
<%= link_to 'Back to Restaurants', restaurants_path %>

<h1><%= @user.name %>'s Profile</h1>

<div class="location">
  <h4>Email: <%= @user.email %></h4>
  <h4>Phone: <%= @user.phone %></h4>
</div>

<%= link_to 'Edit Yo Self', edit_user_path(@user) %>