config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  resources :restaurants do
    resources :reservations
  end

end

app/models/reservation.rb
class Reservation < ApplicationRecord
  validates :date_of_reservation, :time_of_reservation, :number_of_seats, presence: true
  validates :number_of_seats, numericality: {only_integer: true}

  belongs_to :user
  belongs_to :restaurant
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  before_action :load_restaurant
  before_action :ensure_logged_in, only: [:create, :destroy]

  def index
    @reservations = Reservation.all
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  def new
    @reservation = Reservation.new
  end

  def create
    # @reservation = Reservation.new(reservation_params)
    @reservation = @restaurant.reservations.build(reservation_params)
    @reservation.user = current_user
    # @restaurant = Restaurant.find(params[:restaurant_id])

    puts(params[:restaurant_id])

    if @restaurant.available(reservation_params[:number_of_seats].to_i, reservation_params[:time_of_reservation].to_time, params[:restaurant_id])
      if @reservation.save
        redirect_to restaurant_reservations_url, notice: "Reserved!!"
      else
        flash.now[:notice] = "Sorry, you cant sit with us at that time! Please try again, we want you at our table :)"
        render :new
      end
    end
  end

  def edit
    @reservation = Reservation.find(params[:id])
  end

  def update
    @reservation = Reservation.find(params[:id])
      if @reservation.update_attributes(reservation_params)
        redirect_to reservation_url(@reservation)
      else
        render :edit
      end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to reservations_url
  end

  private
  def reservation_params
    params.require(:reservation).permit(:restaurant_id, :date_of_reservation, :time_of_reservation, :number_of_seats)
  end

  def load_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
  #
  # def index
  #   @reservations = Reservation.all
  # end
  #
  # def show
  #   @reservation = Reservation.find(params[:id])
  #
  #   if current_user
  #     @user = @reservation.users.build
  #   end
  # end
  #
  # def new
  #   @reservation = Reservation.new
  #   @restaurant = Restaurant.find(params[:restaurant_id])
  # end
  #
  # # def create
  # #   @reservation = Reservation.new(reservation_params)
  # #   @reservation.user = current_user
  # #     if @reservation.save
  # #       redirect_to restaurant_reservations_url
  # #     else
  # #       render :new
  # #     end
  # # end
  #
  # def create
  #    @reservation = Reservation.new(reservation_params)
  #    @restaurant = Restaurant.find(reservation_params[:restaurant_id])
  #    if @restaurant.available(reservation_params[:number_of_seats].to_i,reservation_params[:time_of_reservation].to_time)
  #      if @reservation.save
  #        redirect_to reservations_url
  #      else
  #        flash.now[:notice] = "Sorry, you cant sit with us at that time! Please try again, we want you at our table :)"
  #        render :new
  #      end
  #    end
  #  end
  #
  # def edit
  #   @reservation = Reservation.find(params[:id])
  #   @restaurant = Restaurant.find(params[:restaurant_id])
  # end
  #
  # def update
  #   @reservation = Reservation.find(params[:id])
  #   @restaurant = Restaurant.find(params[:restaurant_id])
  #     if @reservation.update_attributes(reservation_params)
  #       redirect_to reservation_url(@reservation)
  #     else
  #       render :edit
  #     end
  # end
  #
  # def destroy
  #   @reservation = Reservation.find(params[:id])
  #   @reservation.destroy
  #   redirect_to reservations_url
  # end
  #
  # private
  # def reservation_params
  #   params.require(:reservation).permit(:date_of_reservation, :time_of_reservation, :number_of_seats)
  # end
  #
  # def load_restaurant
  #   @restaurant = Restaurant.find(params[:restaurant_id])
  # end

end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
  <% if @reservation.errors.any? %>
    <div>
      <h2><%= pluralize(@reservation.errors.count, "error")%> Prohibited this product from being saved:</h2>

      <ul>
        <% @reservation.errors.full_message.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="form">
<%= form_for [@restaurant, @reservation] do |f| %>
<%= @restaurant.name.upcase %>
<div class="field">
  <%= f.label "Date:" %>
  <%= f.date_field :date_of_reservation %>
</div>

<div class="field">
  <%= f.label "Time:" %>
  <%= f.time_field :time_of_reservation %>
</div>

<div class="field">
  <%= f.label "Guests:" %>
  <%= f.number_field :number_of_seats%>
</div>

<div class="actions">
  <%= f.submit %>
</div>
<% end %>
</div>

app/views/reservations/create.html.erb
<h1>Reservations#create</h1>
<p>Find me in app/views/reservations/create.html.erb</p>

app/views/reservations/delete.html.erb
<h1>Reservation</h1>
<p>Find me in app/views/reservations/delete.html.erb</p>

app/views/reservations/edit.html.erb
<%= link_to "Back to reservations", @reservation %>

<h2>Edit Reservation</h2>

<%= render 'form', reservation: @reservation %>

app/views/reservations/index.html.erb
<%= link_to "Back to Restaurants", restaurants_url %>

<h1>You're on the List for <em><%= @restaurant.name %></em></h1>

<%= link_to "Add a Reservation", new_restaurant_reservation_path %></br>

<!-- add restaurant name -->
<!-- <h2><%= @restaurant.name %></h2> -->
<% @reservations.each do |reservation| %>
<p>Date: <%= reservation.date_of_reservation %></br>
Time: <%= reservation.time_of_reservation %></br>
Seats: <%= reservation.number_of_seats %></p>
<% end %>

app/views/reservations/new.html.erb
<%= link_to "Back to Restaurants", restaurants_url %>

<h1>Sit with us!</h1>

<%= render 'form', reservation: @reservation %>

app/views/reservations/show.html.erb
<%= link_to "Back to Reservations", reservations_url %>

<h2>Your table is ready!</h2>
<!-- add name of restaurant -->
<p>Date: <%= @reservation.date_of_reservation %></br>
Time: <%= @reservation.time_of_reservation %></br>
Seats: <%= @reservation.number_of_seats %></p>

<%= link_to "Edit", edit_reservation_path(@reservation) %> | <%= link_to "Delete", @reservation, method: :delete, data: {confirm: "Are you sure you want to delete this reservation?"}  %>

app/views/reservations/update.html.erb
<h1>Reservations#update</h1>