config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  resources :restaurants do
    resources :reservations
  end

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

  # validates :name, :description, :cuisine, :price, :street_address, :neighbourhood, :phone, :image, presence: true
  # validates :phone, numericality: {only_integer: true}

  has_many :reservations
  has_many :users, through: :reservations

  def self.search(search)
    # Restaurant.fuzzy_search(search)
    where("cuisine ILIKE ?", "%#{search}%")
     .or(where("name ILIKE ?", "%#{search}%"))
     .or(where("description ILIKE ?", "%#{search}%"))
     .or(where("cuisine ILIKE ?", "%#{search}%"))
     .or(where("price ILIKE ?", "%#{search}%"))
     .or(where("street_address ILIKE ?", "%#{search}%"))
     .or(where("neighbourhood ILIKE ?", "%#{search}%"))
  end

  def available (number_of_seats, time, restaurant_id)
    number_of_seats > 0 && available_capacity(time, restaurant_id) >= number_of_seats
  end

  private

  def available_capacity(time, restaurant_id)
    Restaurant.where(id: restaurant_id).first.capacity - reservations_at(time).sum(:number_of_seats)
    # available_capacity - reservations_at(time).sum(:number_of_seats)
  end

  def reservations_at(time)
    reservations.where(time_of_reservation: time.beginning_of_hour..time.end_of_hour)
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
      @restaurants = Restaurant.all
      if params[:search]
      @restaurants = Restaurant.search(params[:search]).order("created_at DESC")
    else
      @restaurants = Restaurant.all.order('created_at DESC')
    end
  end

def edit
  @restaurant = Restaurant.find(params[:id])
end

def new
  @restaurant = Restaurant.new
end

def show
  @restaurant = Restaurant.find(params[:id])
  if current_user
    @reservation = @restaurant.reservations.build
  end
end

def create
  @restaurant = Restaurant.new(restaurant_params)
  if @restaurant.save
    redirect_to restaurants_url
  else
    render :new
  end
end

def destroy
  @restaurant = Restaurant.find(params[:id])
  @restaurant.destroy
  redirect_to restaurants_url
end

def update
  @restaurants = restaurant.find(restaurant[:id])
  if @restaurant.update_attributes(restaurant_params)
    redirect_to restaurant_url(@restaurant)
  else
    render :edit
  end
end

private

def restaurant_params
    params.require(:restaurant).permit(:name, :description, :cuisine, :price, :street_address, :neighbourhood, :phone, :image, :capacity)
end

end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<div class="form">
<%= form_for @restaurant do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.label :cuisine  %><br>
    <%= f.text_field :cuisine   %>
  </p>
  <p>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </p>
  <p>
    <%= f.label :street_address %><br>
    <%= f.text_field :street_address %>
  </p>
  <p>
    <%= f.label :neighbourhood %><br>
    <%= f.text_field :neighbourhood %>
  </p>
  <p>
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </p>
  <p>
    <%= f.label :image %><br>
    <%= f.text_field :url %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>
</div>

app/views/restaurants/_restaurant.html.erb
<section class="restaurant">
  <%= link_to restaurant.name, restaurant %>
  <% if restaurant.category %>
    <p class="category">Category: <strong><%= restaurant.category.name %></strong></p>
  <% end %>
  <p class="desc"><%= shorten(restaurant.description) %></p>
</section>

app/views/restaurants/_restaurants.html.erb
<% @restaurants.each do |restaurant| %>
  <section class="restaurant">
    <%= link_to restaurant.name, restaurant %>
    <% if restaurant.category %>
      <p class="category">Category: <strong><%= restaurant.category.name %></strong></p>
    <% end %>
    <p class="desc"><%= shorten(restaurant.description) %></p>
  </section>
<% end %>

app/views/restaurants/create.html.erb
<%= link_to 'Back to restaurants', restaurants_path %>

<%= render 'form' %>

app/views/restaurants/destroy.html.erb
<h1>Restaurants#destroy</h1>
<p>Find me in app/views/restaurants/destroy.html.erb</p>

app/views/restaurants/edit.html.erb
<%= link_to 'Back to restaurants', restaurants_path %>

<h1>Edit Restaurant</h1>

<%= render 'form' %>

app/views/restaurants/index.html.erb
<h2>Explore Seat Yoself tables</h2>

<!-- <%= link_to "Add a new Restaurant", new_restaurant_path %> -->

<% @restaurants.each do |restaurant| %>
<div class="restaurant-info">
  <ul>
    <p><%= restaurant.name.upcase %></br><%= restaurant.cuisine %></br><%= restaurant.price %>
    <%= image_tag restaurant.image, :class => "index_image" %>
    <%= link_to "More details", restaurant_path(restaurant) %></p>
  </ul>
</div>
<% end %>

app/views/restaurants/index.js.erb
$('#restaurants').html('<%= j render(@restaurants) %>');

app/views/restaurants/new.html.erb
<%= link_to "Back to Restaurants", restaurants_path %>

<h2>Add a Restaurant</h2>

<%= form_for @restaurant  do |f| %>
<p>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</p>
<p>
  <%= f.label :description %><br>
  <%= f.text_field :description %>
</p>
<p>
  <%= f.label :cuisine  %><br>
  <%= f.text_field :cuisine   %>
</p>
<p>
  <%= f.label :price %><br>
  <%= f.text_field :price %>
</p>
<p>
  <%= f.label :street_address %><br>
  <%= f.text_field :street_address %>
</p>
<p>
  <%= f.label :hood %><br>
  <%= f.text_field :neighbourhood %>
</p>
<p>
  <%= f.label :phone %><br>
  <%= f.text_field :phone %>
</p>




<p>
  <%= f.label :capacity %><br>
  <%= f.number_field :capacity %>
</p>
<p>
  <%= f.label :image %><br>
  <%= f.text_field :url %>
</p>
<p>
  <%= f.submit "Save" %><br>
</p>
<% end %>

app/views/restaurants/show.html.erb
<div id="back-link">
<%= link_to "Back to Restaurants", restaurants_url %>
</div>

<!-- add picture of restaurant -->
<%= image_tag @restaurant.image, :class => "show_image" %>
<div class="restaurant-description">
<h3><strong><%= @restaurant.name %></strong></h3></br>
<%= @restaurant.street_address %>, <%= @restaurant.neighbourhood %> | <%= @restaurant.phone %>
<%= @restaurant.cuisine %> | <%= @restaurant.price %></p>
<p> <%= @restaurant.description %></p>
</div>
<p id="reserve"><%= link_to "RESERVE", new_restaurant_reservation_path(@restaurant)%></p>

app/views/restaurants/update.html.erb
<h1>Restaurants#update</h1>
<p>Find me in app/views/restaurants/update.html.erb</p>