config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  resources :restaurants do
    resources :reservations
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <link rel="logo" type="image/jpg" href="/images/logo_1.jpg" />
  <title>Seatyoself</title>
  <!-- <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet"> -->
  <link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Frank+Ruhl+Libre|Lato|Permanent+Marker" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="title"><h1><a href="/">Seat Yoself! </a><h1></div>

<!-- <div id="header">
<div class="nav">
  <div class="container">
    <ul>
      <li><a href="/users/new">Sign up</a></li><br>
      <li><a href="/sessions/new">Log in</a></li><br> -->
      <!-- <li><a href="">Log out</a></li> -->
    <!-- </ul>
  </div>
</div> -->
<div class="userinfo">
  <% if current_user %>
    Yo, <%= current_user.name %></br><%= link_to "Log out", session_path("current"), :method => :delete %>
  <% else %>
    <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
  <% end %>
</div>

</div>

<% if flash[:notice] %>
  <p id="notice"><%= flash[:notice] %></p>
<% end %>
<% if flash[:alert] %>
  <p id="alert"><%= flash[:alert] %></p>
<% end %>

<%= yield %>

</body>

<!-- <footer>
  <p>&copy Tyler Smith, William Lavell, David Moon, Jessica A., Prisara Morales</p>
</footer> -->

</html>